# Generated by Django 5.1.4 on 2024-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Service Provider Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_person_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Person Name')),
                ('contact_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Id')),
            ],
            options={
                'verbose_name': 'ServiceProvider',
                'verbose_name_plural': 'ServiceProviders',
            },
        ),
    ]
