# Generated by Django 5.1.4 on 2024-12-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_booking_amount'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(help_text='Details of items supplied by this supplier, including quantities.', verbose_name='Items Ordered')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Total Quantity')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Cost (INR)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Order Modified At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='orders.order', verbose_name='Related User Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='supplier.serviceprovider', verbose_name='Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Supplier Order',
                'verbose_name_plural': 'Supplier Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
