# Generated by Django 5.1.4 on 2024-12-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_serviceprovider_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='user',
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='booking_detail',
            field=models.JSONField(default=None, help_text='Details of Booking, including Customer Details, Address, Event Venue, Time of Booking, Event start date, Event end date, Total Amount, Supplier Share, Payment Status', verbose_name='Booking Details'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='event_items_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='event_items_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ordered On'),
        ),
        migrations.CreateModel(
            name='SupplierAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='Bank Account Number')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('micr_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='MICR Code')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch Name')),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='UPI ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('passbook', models.ImageField(upload_to='supplier/passbook', verbose_name='Passbook Image')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='supplier.serviceprovider')),
            ],
            options={
                'verbose_name': 'Supplier Account Detail',
                'verbose_name_plural': 'Supplier Account Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order', to='supplier.supplierorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='supplier.serviceprovider')),
            ],
            options={
                'verbose_name': 'Supplier Transaction',
                'verbose_name_plural': 'Supplier Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
