# Generated by Django 5.1.4 on 2024-12-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Advance Amount')),
                ('advance_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Advance Payment ID')),
                ('advance_payment_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Advance Payment Transaction ID')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pending Amount')),
                ('pending_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pending Payment ID')),
                ('pending_payment_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pending Payment Transaction ID')),
                ('advance_date', models.DateTimeField(blank=True, null=True, verbose_name='Advance Payment Date')),
                ('pending_date', models.DateTimeField(blank=True, null=True, verbose_name='Pending Payment Date')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
            ],
        ),
    ]
