# Generated by Django 5.1.4 on 2024-12-13 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_gatheringsize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyingForChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'PartyingForChoice',
                'verbose_name_plural': 'PartyingForChoices',
            },
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_area', models.CharField(blank=True, max_length=500, null=True, verbose_name='Plot Area (in feets)')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('gathering_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gatheringsize', verbose_name='Gathering For')),
                ('partying_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.partyingforchoice', verbose_name='Partying For')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserRequirement',
                'verbose_name_plural': 'UserRequirements',
            },
        ),
    ]
