services:
  web-ots:
    build:
      context: ..
      dockerfile: deploy/image/Dockerfile
    command: python manage.py runserver 0.0.0.0:8400
    volumes:
      - ../src:/app/src
    ports:
      - "8400:8400"
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'vams-ots'
      POSTGRES_USER: 'root'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_PORT: '3306'
    # depends_on:
    #   # - db
    #   - redis
    restart: always

  # celery:
  #   build:
  #     context: ..
  #     dockerfile: deploy/image/Dockerfile
  #   command: celery -A opcua_provider_service worker --loglevel=info
  #   volumes:
  #     - ../src:/app/opcua/provider
  #   environment:
  #     POSTGRES_PASSWORD: 'Shekhar123#'
  #     POSTGRES_DB: 'opcua'
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_HOST: 'host.docker.internal'
  #     POSTGRES_PORT: '5433'
  #   depends_on:
  #     # - db
  #     - redis
  #   restart: always

  # redis:
  #   image: redis:alpine
