# Generated by Django 5.1.4 on 2024-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceotp',
            name='session',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
