# Generated by Django 5.1.4 on 2024-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_deviceotp_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=10),
        ),
    ]
