# Generated by Django 5.1.4 on 2024-12-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_seller',
            new_name='is_supplier',
        ),
    ]
