# Generated by Django 5.1.4 on 2024-12-13 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Booking Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Hours'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_full_payment_paid',
            field=models.BooleanField(default=False, verbose_name='Is Full Payment Completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_partial_payment_paid',
            field=models.BooleanField(default=False, verbose_name='Is Booking Payment Completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date and Time'),
            preserve_default=False,
        ),
    ]
