# Generated by Django 5.1.4 on 2024-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_booking_amount_order_end_datetime_order_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date and Time'),
        ),
    ]
