# Generated by Django 5.1.4 on 2024-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_end_datetime_alter_order_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Booking Amount'),
        ),
    ]
